version: '3.8'

services:
  flask-app:
    image: alexshevdev/wog_alexshev:v1.5
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8777:8000"
    volumes:
      - "./Scores.txt:/Scores.txt"
